# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    container_name: paco-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: paco
      MYSQL_DATABASE: paco
      MYSQL_USER: paco
      MYSQL_PASSWORD: paco
    volumes:
      - paco-data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: paco-adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  paco-data: